class DateTimeFormat {
  static const String formatDateAndMonth = 'dd/MM';
  static const String formatMonthYear = 'MM/yyyy';
  static const String formatWeekend = 'EEE';
  static const String formatEventByDay = "dd/MM/yyyy";
  static const String formatYear = "yyyy";
  static const String formatDate = "dd/MM/yyyy";
  static const String formatDateShortYear = "dd/MM/yy";
  static const String formatDateShort = "dd/MM/yyyy";
  static const String ddMMyy = "dd/MM/yy";
  static const String formatDateReq = "dd/MM/yyyy HH:mm";
  static const String formatDateNote = "HH:mm dd/MM/yyyy";
  static const String formatDateNote1 = "HH:mm - dd/MM/yyyy";
  static const String formatDateTime = "dd/MM/yyyy HH:mm:ss";
  static const String formatDateMission2 = "dd-MM-yyyy";
  static const String formatDateTime1 = "dd/MM/yyyyHH:mm:ss";
  static const String formatDateTime2 = "yyyy-MM-ddHH:mm:ss";
  static const String formatShow = "HH:mm dd/MM/yyyy";
  static const String formatShowLine = "HH:mm dd/MM/yy";
  static const String formatDateVisit = "MM.dd.yyyy HH:mm:ss";
  static const String formatTime = "HH:mm";
  static const String formatTimeValue = "HH:mm:ss";
  static const String formatTimeCar = "HH:mm-dd/MM";
  static const String formatDateDuty = "yyyyMMdd";
  static const String formatDateMission = "dd-MM-yyyy";
  static const String formatDateSecurity = "HH'h'mm dd/MM/yyyy";
  static const String formatDateHour = "HH'h'mm";
  static const String formatHour = "HH:mm aa";
}
